### ISSUE TITLE
Allow for multiple return types

### ISSUE THREAD

**Issue by astridlol** [astridlol/routify#3]
Documenting all of the return types in needed in my opinion, as not every route is guaranteed to just send a default 200 status code, with the response given.

I think adding something like `@200: <body>` would be good, but then it most likely won't account for responses of the same status code (ex: 2 different response types both with the 400 status code)

If anyone has ideas, feel free to comment

**Comment by eyob-muktar** [comment]
How about using the status codes as annotations and making the responses array of objects?

**Comment by astridlol** [comment]
> How about using the status codes as annotations and making the responses array of objects?

Interesting idea, I'll look into that

**Comment by astridlol** [comment]
Added in f874f08
